### ISSUE TITLE
Apprise:// not working with or without tags

### ISSUE THREAD

**Issue by pushc6** [caronc/apprise-api#109]
:mega: **Notification Service(s) Impacted**
Apprise:// (all notifications)

:lady_beetle: **Describe the bug**
When using CLI or apprise:// from another apprise instance I get the below error. 

[WARNING] django.request: Failed Dependency: /notify/apprise

when passing ?tags= I get the following:

03/13/2023 9:20:36 AM
2023-03-13 08:20:36,398 [ERROR] django.request: Internal Server Error: /notify/apprise
03/13/2023 9:20:36 AM
Traceback (most recent call last):
03/13/2023 9:20:36 AM
  File "/usr/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
03/13/2023 9:20:36 AM
    response = get_response(request)
03/13/2023 9:20:36 AM
  File "/usr/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
03/13/2023 9:20:36 AM
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
03/13/2023 9:20:36 AM
  File "/usr/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
03/13/2023 9:20:36 AM
    return self.dispatch(request, *args, **kwargs)
03/13/2023 9:20:36 AM
  File "/usr/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
03/13/2023 9:20:36 AM
    return bound_method(*args, **kwargs)
03/13/2023 9:20:36 AM
  File "/usr/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
03/13/2023 9:20:36 AM
    response = view_func(request, *args, **kwargs)
03/13/2023 9:20:36 AM
  File "/usr/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
03/13/2023 9:20:36 AM
    response = view_func(request, *args, **kwargs)
03/13/2023 9:20:36 AM
  File "/usr/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
03/13/2023 9:20:36 AM
    return handler(request, *args, **kwargs)
03/13/2023 9:20:36 AM
  File "/app/apprise-api/apprise_api/./api/views.py", line 622, in post
03/13/2023 9:20:36 AM
    if not TAG_VALIDATION_RE.match(content.get('tag')):
03/13/2023 9:20:36 AM
TypeError: expected string or bytes-like object

:bulb: **Screenshots and Logs**
![Screen Shot 2023-03-13 at 09 22 24](https://user-images.githubusercontent.com/28690966/224714330-5de7d0b6-d540-477d-9b83-0ce02d5a3066.png)
![Screen Shot 2023-03-13 at 09 22 08](https://user-images.githubusercontent.com/28690966/224714335-fb8e56d8-2e1a-4cf2-a75c-8e7918c4aae9.png)

:computer: **Your System Details:**
Ubuntu - Docker - Latest LinuxServer.io apprise-api build

:crystal_ball: **Additional context**
If I send notifications via the apprise-api UI tool they work. But via the CLI or via apprise:// from another apprise instance fails. None of my notifications are working right now.

**Comment by caronc** [comment]
This is fixed now; i was able to reproduce your case.

Thank you for reporting this.

**Comment by pushc6** [comment]
Awesome, thanks @caronc!
